version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    # Uncomment the following lines if you need to connect to a backend service
    # environment:
    #   - REACT_APP_API_URL=http://backend:5000/api
    # depends_on:
    #   - backend
  
  # Example backend service configuration (uncomment if needed)
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production 